In [4]:
import tensorflow as tf
import keras
 # Building the CNN

# Importing the Keras libraries and packages'''
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

ModuleNotFoundError: No module named 'tensorflow'

In [3]:

# coding: utf-8

# In[ ]:

import tensorflow as tf
import keras
Building the CNN
Importing the Keras libraries and packages'''
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

SyntaxError: invalid syntax (<ipython-input-3-5302a35033ff>, line 7)

In [5]:
Installing Theano

SyntaxError: invalid syntax (<ipython-input-5-eaf1f0d97b2b>, line 1)

In [7]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
os.getcwd()

'C:\\Users\\ABHIJEET-PC\\Desktop\\AI & ML'

In [8]:
print(os.getcwd())

C:\Users\ABHIJEET-PC\Desktop\AI & ML


In [13]:

# Importing the dataset
dataset = pd.read_csv('airline-passengers.csv')

X = dataset.iloc[:, 3:13].values

y = dataset.iloc[:, 13].values

FileNotFoundError: [Errno 2] File b'airline-passengers.csv' does not exist: b'airline-passengers.csv'

In [10]:
# Installing Theano
#!pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
#!pip install tensorflow

# Installing Keras
#!pip install --upgrade keras
#!pip install keras

#!conda upgrade pandas pytables h5py

In [11]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
os.getcwd()

'C:\\Users\\ABHIJEET-PC\\Desktop\\AI & ML'

In [14]:
# Importing the dataset
dataset = pd.read_csv('airline-passengers.csv')

FileNotFoundError: [Errno 2] File b'airline-passengers.csv' does not exist: b'airline-passengers.csv'

In [15]:
# Dummy Vars & Encoders
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [16]:
dataset2 = ['Pizza','Burger','Bread','Bread','Bread','Burger','Pizza','Burger']

In [17]:
values = array(dataset2)
print(values)

['Pizza' 'Burger' 'Bread' 'Bread' 'Bread' 'Burger' 'Pizza' 'Burger']


In [18]:
label_encoder = LabelEncoder()

integer_encoded = label_encoder.fit_transform(values)

print(integer_encoded)

[2 1 0 0 0 1 2 1]


In [19]:
onehot = OneHotEncoder(sparse=False)

In [20]:
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
print(integer_encoded)

[[2]
 [1]
 [0]
 [0]
 [0]
 [1]
 [2]
 [1]]


In [21]:
onehot_encoded = onehot.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [24]:

# inverted_result = label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
print(inverted_result)

NameError: name 'inverted_result' is not defined

In [25]:
#inverted_result = label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
#print(inverted_result)

# Encoding categorical data
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [26]:

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [29]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X
print(X)

NameError: name 'X' is not defined

In [30]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X
print(X)

X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

NameError: name 'X' is not defined

In [31]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

X.shape

tmpDF = pd.DataFrame(X)
tmpDF

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X

tmpDF = pd.DataFrame(X)
tmpDF


X.shape


X = X[:, 1:]
X

X.shape

NameError: name 'X' is not defined

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

NameError: name 'X' is not defined

In [33]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [34]:
import os

In [36]:
# Importing the training set
dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')
training_set = dataset_train.iloc[:, 1:2].values
dataset_train.head()

FileNotFoundError: [Errno 2] File b'Google_Stock_Price_Train.csv' does not exist: b'Google_Stock_Price_Train.csv'

In [41]:
# Importing the training set
dataset_train =  pd.read_csv('Employee-Dataset-AC1.csv')
training_set = dataset_train.iloc[:, 1:2].values
dataset_train.head()

FileNotFoundError: [Errno 2] File b'Employee-Dataset-AC1.csv' does not exist: b'Employee-Dataset-AC1.csv'

In [40]:
# Feature Scaling
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
training_set_scaled

NameError: name 'training_set' is not defined